### ISSUE TITLE
启动nonebot时报错（缺少配置）

### ISSUE THREAD

**Issue by MCyudix** [Ljzd-PRO/nonebot-plugin-dg-lab-play#54]
![image](https://github.com/user-attachments/assets/8d74c42b-1109-4020-ba1d-7fa56b467991)

**Comment by Ljzd-PRO** [comment]
看上去是创建的nonebot机器人项目有点问题，应该不是插件的问题，说是机器人项目的 `pyproject.toml` 里缺少了 `[tool.nonebot]` 这个部分，这个部分好像一般是会写你要加载的插件名称的。
如果项目插件比较少的话，可以用 `nb-cli` 重新创建一个机器人项目
