### ISSUE TITLE
nb安装会出现notfound

### ISSUE THREAD

**Issue by yokoyamamio** [Ljzd-PRO/nonebot-plugin-dg-lab-play#7]

**Comment by Ljzd-PRO** [comment]
后面再加 `-i https://pypi.org/simple` 试试？

**Comment by yokoyamamio** [comment]
root@ECS1033:~/qb2/qb/.venv/lib/python3.10/site-packages# nb plugin install nonebot-plugin-dg-lab-play -i https://pypi.org/simple
Package nonebot-plugin-dg-lab-play not found.``

**Comment by yokoyamamio** [comment]
还是不行（

**Comment by Ljzd-PRO** [comment]
对照了一下，需要等 nonebot 发布新版本了才能用 nb-cli 安装。目前需要手动进入创建好的机器人项目的虚拟环境里，用 pip 安装。

在机器人项目目录下用
```bash
source activate .venv/bin/activate
```
然后
```bash
pip install nonebot-plugin-dg-lab-play
```

**Comment by Ljzd-PRO** [comment]
> 对照了一下，需要等 nonebot 发布新版本了才能用 nb-cli 安装。目前需要手动进入创建好的机器人项目的虚拟环境里，用 pip 安装。
> 
> 在机器人项目目录下运行
> 
> ```shell
> source activate .venv/bin/activate
> ```
> 
> 然后运行
> 
> ```shell
> pip install nonebot-plugin-dg-lab-play
> ```
> 
> 之后用
> 
> ```shell
> deactivate
> ```
> 
> 退出虚拟环境

nonebot 新版本已发布（https://github.com/nonebot/nonebot2/releases/tag/v2.3.2）
